
version: "3.9"

services:           # <-- THIS IS REQUIRED
  db:
    image: postgres:15
    container_name: finance_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

  app:              # <-- must be under services
    build: .
    container_name: finance_app
    environment:
      - ALPHA_VANTAGE_API_KEY=B5PQDKWDCCISZ2ZQ
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=finance
    ports:
      - "3000:3000"
    depends_on:
      - db
    # volumes:
    #   - .:/usr/src/app


